services:
  server:
    container_name: vibewriter-server
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: postgres:17-alpine
    container_name: vibewriter-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # already have postgres locally

volumes:
  db_data:
# in docker /var/lib/containers is the location for containers and for volumes /var/lib/containers/storage/volumes,

